# Generated by Django 3.2.7 on 2021-09-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210912_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
